# Generated by Django 5.0.14 on 2026-02-14 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpgaverKode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_nr', models.CharField(max_length=50, unique=True, verbose_name='KodeNr')),
                ('beskrivelse', models.CharField(max_length=255, verbose_name='Beskrivelse')),
            ],
            options={
                'verbose_name': 'Opgavekode',
                'verbose_name_plural': 'Opgavekoder',
                'ordering': ['kode_nr'],
            },
        ),
        migrations.CreateModel(
            name='BrugerIndstillingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_x', models.IntegerField(blank=True, null=True)),
                ('window_y', models.IntegerField(blank=True, null=True)),
                ('window_width', models.IntegerField(blank=True, null=True)),
                ('window_height', models.IntegerField(blank=True, null=True)),
                ('bruger', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='time_indstillinger', to=settings.AUTH_USER_MODEL, verbose_name='Bruger')),
            ],
            options={
                'verbose_name': 'Bruger Time Indstilling',
                'verbose_name_plural': 'Bruger Time Indstillinger',
            },
        ),
        migrations.CreateModel(
            name='BrugerProfilTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(blank=True, max_length=255, null=True, verbose_name='Alias')),
                ('sortering', models.IntegerField(blank=True, null=True, verbose_name='Sortering')),
                ('bruger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_profiler', to=settings.AUTH_USER_MODEL, verbose_name='Bruger')),
                ('opgave_kode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tidsregistrering.opgaverkode', verbose_name='Opgavekode')),
            ],
            options={
                'verbose_name': 'Bruger Time Profil',
                'verbose_name_plural': 'Bruger Time Profiler',
                'ordering': ['sortering', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Tidreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(blank=True, max_length=255, null=True, verbose_name='Alias')),
                ('fra_tid', models.DateTimeField(verbose_name='Fra tid')),
                ('til_tid', models.DateTimeField(blank=True, null=True, verbose_name='Til tid')),
                ('tid', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tid')),
                ('kommentar', models.TextField(blank=True, null=True, verbose_name='Kommentar')),
                ('aktiv', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('bruger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tidsregistreringer', to=settings.AUTH_USER_MODEL, verbose_name='Bruger')),
                ('opgave_kode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registreringer', to='tidsregistrering.opgaverkode', verbose_name='Opgavekode')),
            ],
            options={
                'verbose_name': 'Tidsregistrering',
                'verbose_name_plural': 'Tidsregistreringer',
                'ordering': ['-fra_tid'],
            },
        ),
    ]
