# Generated by Django 5.0.14 on 2026-02-14 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tidsregistrering', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KoderGrupper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gruppe', models.CharField(max_length=6, unique=True, verbose_name='Gruppe')),
                ('beskrivelse', models.CharField(blank=True, max_length=255, null=True, verbose_name='Beskrivelse')),
            ],
            options={
                'verbose_name': 'Kodegruppe',
                'verbose_name_plural': 'Kodegrupper',
                'ordering': ['gruppe'],
            },
        ),
        migrations.AddField(
            model_name='opgaverkode',
            name='mtime',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Mtime'),
        ),
        migrations.AddField(
            model_name='opgaverkode',
            name='gruppe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tidsregistrering.kodergrupper', to_field='gruppe', verbose_name='Gruppe'),
        ),
    ]
