# Generated by Django 5.0.14 on 2026-03-10 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_company_uitranslation_alter_team_navn_team_company_and_more'),
        ('tidsregistrering', '0002_kodergrupper_opgaverkode_mtime_opgaverkode_gruppe'),
    ]

    operations = [
        migrations.AddField(
            model_name='kodergrupper',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kodegrupper', to='core.company'),
        ),
        migrations.AddField(
            model_name='opgaverkode',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opgavekoder', to='core.company'),
        ),
        migrations.AddField(
            model_name='tidreg',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tidsregistreringer', to='core.company'),
        ),
        migrations.AlterField(
            model_name='opgaverkode',
            name='gruppe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tidsregistrering.kodergrupper', verbose_name='Gruppe'),
        ),
        migrations.AlterField(
            model_name='kodergrupper',
            name='gruppe',
            field=models.CharField(max_length=6, verbose_name='Gruppe'),
        ),
        migrations.AlterField(
            model_name='opgaverkode',
            name='kode_nr',
            field=models.CharField(max_length=50, verbose_name='KodeNr'),
        ),
        migrations.AlterUniqueTogether(
            name='kodergrupper',
            unique_together={('company', 'gruppe')},
        ),
        migrations.AlterUniqueTogether(
            name='opgaverkode',
            unique_together={('company', 'kode_nr')},
        ),
    ]
