# Generated by Django 5.2.11 on 2026-03-20 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0010_userprofile_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flowchart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=255)),
                ('beskrivelse', models.TextField(blank=True)),
                ('oprettet', models.DateTimeField(auto_now_add=True)),
                ('opdateret', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flowcharts', to='core.company')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flowcharts', to='core.team')),
            ],
            options={
                'verbose_name': 'Flowchart',
                'verbose_name_plural': 'Flowcharts',
                'ordering': ['navn'],
            },
        ),
        migrations.CreateModel(
            name='FlowchartNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=100)),
                ('navn', models.CharField(max_length=255)),
                ('beskrivelse', models.TextField(blank=True)),
                ('farve', models.CharField(default='#3b82f6', max_length=20)),
                ('form_type', models.CharField(choices=[('rectangle', 'Rectangle (Process)'), ('diamond', 'Diamond (Decision)'), ('oval', 'Oval (Start/End)')], default='rectangle', max_length=20)),
                ('x_pos', models.FloatField(default=0)),
                ('y_pos', models.FloatField(default=0)),
                ('bredde', models.FloatField(default=160)),
                ('hoejde', models.FloatField(default=60)),
                ('flowchart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='flowchart.flowchart')),
            ],
            options={
                'verbose_name': 'Flowchart Node',
                'verbose_name_plural': 'Flowchart Nodes',
                'unique_together': {('flowchart', 'node_id')},
            },
        ),
        migrations.CreateModel(
            name='FlowchartEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_id', models.CharField(max_length=100)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('flowchart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='flowchart.flowchart')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='flowchart.flowchartnode')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='flowchart.flowchartnode')),
            ],
            options={
                'verbose_name': 'Flowchart Edge',
                'verbose_name_plural': 'Flowchart Edges',
                'unique_together': {('flowchart', 'edge_id')},
            },
        ),
    ]
