# Generated by Django 5.2.11 on 2026-03-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applinks', '0001_initial'),
        ('core', '0005_userprofile_vidensbank_category_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppPurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='applink',
            name='group',
        ),
        migrations.RemoveField(
            model_name='applink',
            name='purpose',
        ),
        migrations.AddField(
            model_name='applink',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='app_links', to='core.team'),
        ),
        migrations.AddField(
            model_name='applink',
            name='purposes',
            field=models.ManyToManyField(blank=True, related_name='app_links', to='applinks.apppurpose'),
        ),
    ]
