# Generated by Django 5.0.14 on 2026-03-10 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applinks', '0002_apppurpose_remove_applink_group_and_more'),
        ('core', '0006_company_uitranslation_alter_team_navn_team_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applink',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_links', to='core.company'),
        ),
        migrations.AddField(
            model_name='apppurpose',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_purposes', to='core.company'),
        ),
        migrations.AlterField(
            model_name='apppurpose',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
