# Generated by Django 5.0.14 on 2026-02-04 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opgave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('beskrivelse', models.TextField(blank=True, verbose_name='Beskrivelse (HTML)')),
                ('status', models.CharField(choices=[('BACKLOG', 'Backlog'), ('TODO', 'To Do'), ('IN_PROGRESS', 'Igang'), ('TEST', 'Test'), ('DONE', 'Færdig')], db_index=True, default='BACKLOG', max_length=20)),
                ('prioritet', models.CharField(choices=[('LOW', 'Lav'), ('MEDIUM', 'Middel'), ('HIGH', 'Høj'), ('URGENT', 'Haster')], default='MEDIUM', max_length=20)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('oprettet', models.DateTimeField(auto_now_add=True)),
                ('opdateret', models.DateTimeField(auto_now=True)),
                ('index', models.PositiveIntegerField(default=0, help_text='Sortering inden for status')),
                ('ansvarlig', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ansvarlige_opgaver', to=settings.AUTH_USER_MODEL)),
                ('oprettet_af', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oprettede_opgaver', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Opgave',
                'verbose_name_plural': 'Opgaver',
                'ordering': ['index', '-opdateret'],
            },
        ),
        migrations.CreateModel(
            name='OpgaveKommentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tekst', models.TextField()),
                ('oprettet', models.DateTimeField(auto_now_add=True)),
                ('bruger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('opgave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kommentarer', to='opgaver.opgave')),
            ],
            options={
                'ordering': ['oprettet'],
            },
        ),
    ]
