# Generated by Django 5.0.14 on 2026-02-06 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opgaver', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpgaveStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gammel_status', models.CharField(choices=[('BACKLOG', 'Backlog'), ('TODO', 'To Do'), ('IN_PROGRESS', 'Igang'), ('TEST', 'Test'), ('DONE', 'Færdig')], max_length=20)),
                ('ny_status', models.CharField(choices=[('BACKLOG', 'Backlog'), ('TODO', 'To Do'), ('IN_PROGRESS', 'Igang'), ('TEST', 'Test'), ('DONE', 'Færdig')], max_length=20)),
                ('tidspunkt', models.DateTimeField(auto_now_add=True)),
                ('bruger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('opgave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='opgaver.opgave')),
            ],
            options={
                'ordering': ['-tidspunkt'],
            },
        ),
    ]
