# Generated by Django 5.0.14 on 2026-02-06 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opgaver', '0002_opgavestatuslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='opgave',
            name='kommentar_antal',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
