# Generated by Django 5.0.14 on 2026-02-06 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opgaver', '0003_opgave_kommentar_antal'),
    ]

    operations = [
        migrations.AddField(
            model_name='opgave',
            name='status_direction',
            field=models.IntegerField(default=0, help_text='-1: Retur, 0: Samme, 1: Frem'),
        ),
    ]
