# Generated by Django 5.0.14 on 2026-02-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opgaver', '0004_opgave_status_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='opgave',
            name='arkiveret',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Arkiveret'),
        ),
    ]
