# Generated by Django 5.0.14 on 2026-02-08 18:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opgaver', '0005_opgave_arkiveret'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='opgave',
            name='ansvarlige',
            field=models.ManyToManyField(blank=True, related_name='opgaver_som_ansvarlig', to=settings.AUTH_USER_MODEL, verbose_name='Ansvarlige'),
        ),
    ]
