# Generated by Django 5.0.14 on 2026-02-08 18:33

from django.db import migrations

def copy_ansvarlig(apps, schema_editor):
    Opgave = apps.get_model('opgaver', 'Opgave')
    for opgave in Opgave.objects.all():
        if opgave.ansvarlig:
            opgave.ansvarlige.add(opgave.ansvarlig)

class Migration(migrations.Migration):

    dependencies = [
        ('opgaver', '0006_opgave_ansvarlige'),
    ]

    operations = [
        migrations.RunPython(copy_ansvarlig),
    ]
