# Generated by Django 5.0.14 on 2026-02-08 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opgaver', '0007_auto_20260208_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opgave',
            name='ansvarlig',
        ),
    ]
