# Generated by Django 5.0.14 on 2026-02-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opgaver', '0009_alter_opgave_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opgave',
            name='status',
            field=models.CharField(choices=[('BACKLOG', 'Backlog'), ('ON_HOLD', 'On Hold'), ('TODO', 'To Do'), ('IN_PROGRESS', 'Igang'), ('TEST', 'Test'), ('DONE', 'Færdig')], db_index=True, default='BACKLOG', max_length=20),
        ),
        migrations.AlterField(
            model_name='opgavestatuslog',
            name='gammel_status',
            field=models.CharField(choices=[('BACKLOG', 'Backlog'), ('ON_HOLD', 'On Hold'), ('TODO', 'To Do'), ('IN_PROGRESS', 'Igang'), ('TEST', 'Test'), ('DONE', 'Færdig')], max_length=20),
        ),
        migrations.AlterField(
            model_name='opgavestatuslog',
            name='ny_status',
            field=models.CharField(choices=[('BACKLOG', 'Backlog'), ('ON_HOLD', 'On Hold'), ('TODO', 'To Do'), ('IN_PROGRESS', 'Igang'), ('TEST', 'Test'), ('DONE', 'Færdig')], max_length=20),
        ),
    ]
