# Generated by Django 5.2.11 on 2026-02-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opgaver', '0010_alter_opgave_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opgave',
            name='status',
            field=models.CharField(choices=[('BACKLOG', 'Backlog'), ('TODO', 'To Do'), ('IN_PROGRESS', 'Igang'), ('TEST', 'Test'), ('DONE', 'Færdig'), ('ON_HOLD', 'On Hold')], db_index=True, default='BACKLOG', max_length=20),
        ),
        migrations.AlterField(
            model_name='opgavestatuslog',
            name='gammel_status',
            field=models.CharField(choices=[('BACKLOG', 'Backlog'), ('TODO', 'To Do'), ('IN_PROGRESS', 'Igang'), ('TEST', 'Test'), ('DONE', 'Færdig'), ('ON_HOLD', 'On Hold')], max_length=20),
        ),
        migrations.AlterField(
            model_name='opgavestatuslog',
            name='ny_status',
            field=models.CharField(choices=[('BACKLOG', 'Backlog'), ('TODO', 'To Do'), ('IN_PROGRESS', 'Igang'), ('TEST', 'Test'), ('DONE', 'Færdig'), ('ON_HOLD', 'On Hold')], max_length=20),
        ),
    ]
