# Generated by Django 5.2.11 on 2026-02-13 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_team'),
        ('opgaver', '0011_alter_opgave_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opgave',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opgaver', to='core.team', verbose_name='Team'),
        ),
    ]
