# Generated by Django 5.0.14 on 2026-02-27 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userprofile_vidensbank_category_order'),
        ('opgaver', '0012_opgave_team'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PinboardPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('beskrivelse', models.TextField(blank=True)),
                ('oprettet', models.DateTimeField(auto_now_add=True)),
                ('opdateret', models.DateTimeField(auto_now=True)),
                ('oprettet_af', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oprettede_prikbord_posts', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prikbord_posts', to='core.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Prikbord Post',
                'verbose_name_plural': 'Prikbord Posts',
                'ordering': ['-oprettet'],
            },
        ),
        migrations.CreateModel(
            name='PinboardPostEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluering', models.CharField(choices=[('GOD_IDE', 'God idé'), ('INGEN_MENING', 'Ingen mening'), ('SEE_COMMENT', 'Se kommentar'), ('LÆST', 'Læst')], max_length=20)),
                ('oprettet', models.DateTimeField(auto_now_add=True)),
                ('bruger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_evalueringer', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evalueringer', to='opgaver.pinboardpost')),
            ],
            options={
                'verbose_name': 'Post Evaluering',
                'verbose_name_plural': 'Post Evalueringer',
                'unique_together': {('post', 'bruger')},
            },
        ),
    ]
