# Generated by Django 5.0.14 on 2026-02-27 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opgaver', '0013_pinboardpost_pinboardpostevaluation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinboardpostevaluation',
            name='evaluering',
            field=models.CharField(choices=[('GOD_IDE', 'God idé'), ('INGEN_MENING', 'Ved ikke'), ('LÆST', 'Læst')], max_length=20),
        ),
        migrations.CreateModel(
            name='PinboardPostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tekst', models.TextField()),
                ('oprettet', models.DateTimeField(auto_now_add=True)),
                ('bruger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prikbord_kommentarer', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kommentarer', to='opgaver.pinboardpost')),
            ],
            options={
                'verbose_name': 'Prikbord Kommentar',
                'verbose_name_plural': 'Prikbord Kommentarer',
                'ordering': ['oprettet'],
            },
        ),
    ]
