# Generated by Django 5.0.14 on 2026-02-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opgaver', '0014_alter_pinboardpostevaluation_evaluering_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinboardpost',
            name='arkiveret',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Arkiveret'),
        ),
    ]
