# Generated by Django 5.0.14 on 2026-03-10 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_company_uitranslation_alter_team_navn_team_company_and_more'),
        ('opgaver', '0015_pinboardpost_arkiveret'),
    ]

    operations = [
        migrations.AddField(
            model_name='opgave',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opgaver', to='core.company'),
        ),
        migrations.AddField(
            model_name='pinboardpost',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prikbord_posts', to='core.company'),
        ),
    ]
