# Generated by Django 5.0.14 on 2026-01-07 18:44

import django.db.models.deletion
import vidensbank.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VidensKategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=100, unique=True)),
                ('beskrivelse', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Videns Kategori',
                'verbose_name_plural': 'Videns Kategorier',
                'ordering': ['navn'],
            },
        ),
        migrations.CreateModel(
            name='Viden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=255)),
                ('indhold', models.TextField(verbose_name='Indhold (HTML)')),
                ('link', models.CharField(blank=True, help_text='Link til ekstern side eller dokument', max_length=512, null=True)),
                ('fil', models.FileField(blank=True, null=True, upload_to=vidensbank.models.vidensbank_dokument_path)),
                ('oprettet', models.DateTimeField(auto_now_add=True)),
                ('opdateret', models.DateTimeField(auto_now=True)),
                ('oprettet_af', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oprettet_viden', to=settings.AUTH_USER_MODEL)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artikler', to='vidensbank.videnskategori')),
            ],
            options={
                'verbose_name': 'Videns artikel',
                'verbose_name_plural': 'Vidensbank',
                'ordering': ['-oprettet'],
            },
        ),
    ]
