# Generated by Django 5.0.14 on 2026-01-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidensbank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videnskategori',
            name='farve',
            field=models.CharField(default='#2563eb', help_text='Hex farvekode (f.eks. #2563eb)', max_length=7),
        ),
    ]
