# Generated by Django 5.0.14 on 2026-01-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidensbank', '0002_videnskategori_farve'),
    ]

    operations = [
        migrations.AddField(
            model_name='viden',
            name='slug',
            field=models.SlugField(blank=True, help_text="Unik identifikator til brug i links (f.eks. 'gem-chat-app')", max_length=255, null=True, unique=True),
        ),
    ]
