# Generated by Django 5.0.14 on 2026-01-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidensbank', '0003_viden_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='HjaelpPunkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_navn', models.CharField(help_text="Unik kode brugt i frontend (f.eks. 'CHAT_SIDEBAR_HELP')", max_length=100, unique=True)),
                ('alias', models.CharField(help_text="Beskrivende navn så vi ved hvor det bruges (f.eks. 'Hjælp i chat sidebaren')", max_length=255)),
                ('artikler', models.ManyToManyField(blank=True, related_name='hjaelp_punkter', to='vidensbank.viden')),
            ],
            options={
                'verbose_name': 'Hjælpepunkt',
                'verbose_name_plural': 'Hjælpepunkter',
                'ordering': ['alias'],
            },
        ),
    ]
