# Generated by Django 5.0.14 on 2026-01-12 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidensbank', '0004_hjaelppunkt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hjaelppunkt',
            old_name='artikler',
            new_name='artikler_legacy',
        ),
        migrations.AlterField(
            model_name='hjaelppunkt',
            name='artikler_legacy',
            field=models.ManyToManyField(blank=True, related_name='hjaelp_punkter_legacy', to='vidensbank.viden'),
        ),
        migrations.CreateModel(
            name='HjaelpPunktViden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sortering', models.PositiveIntegerField(default=0)),
                ('hjaelp_punkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hjaelp_punkt_links', to='vidensbank.hjaelppunkt')),
                ('viden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viden_hjaelp_links', to='vidensbank.viden')),
            ],
            options={
                'verbose_name': 'Hjælpepunkt Artikel Link',
                'verbose_name_plural': 'Hjælpepunkt Artikel Links',
                'ordering': ['sortering'],
                'unique_together': {('hjaelp_punkt', 'viden')},
            },
        ),
        migrations.AddField(
            model_name='hjaelppunkt',
            name='artikler',
            field=models.ManyToManyField(blank=True, related_name='hjaelp_punkter', through='vidensbank.HjaelpPunktViden', to='vidensbank.viden'),
        ),
    ]
