# Generated by Django 5.0.14 on 2026-01-12 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vidensbank', '0005_hjaelppunkt_artikler_legacy_hjaelppunktviden_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hjaelppunkt',
            name='artikler_legacy',
        ),
    ]
