# Generated by Django 5.0.14 on 2026-01-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidensbank', '0006_remove_hjaelppunkt_artikler_legacy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viden',
            options={'ordering': ['-favorit', '-oprettet'], 'verbose_name': 'Videns artikel', 'verbose_name_plural': 'Vidensbank'},
        ),
        migrations.AddField(
            model_name='viden',
            name='arkiveret',
            field=models.BooleanField(default=False, verbose_name='Arkiveret'),
        ),
        migrations.AddField(
            model_name='viden',
            name='favorit',
            field=models.BooleanField(default=False, verbose_name='Favorit'),
        ),
    ]
