# Generated by Django 5.0.14 on 2026-01-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidensbank', '0007_alter_viden_options_viden_arkiveret_viden_favorit'),
    ]

    operations = [
        migrations.AddField(
            model_name='videnskategori',
            name='er_privat',
            field=models.BooleanField(default=False, help_text='Hvis markeret, kan artikler i denne kategori kun ses af den person der har oprettet dem.', verbose_name='Privat kategori'),
        ),
    ]
