# Generated by Django 5.0.14 on 2026-02-14 09:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidensbank', '0008_videnskategori_er_privat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viden',
            options={'ordering': ['-oprettet'], 'verbose_name': 'Videns artikel', 'verbose_name_plural': 'Vidensbank'},
        ),
        migrations.RemoveField(
            model_name='viden',
            name='favorit',
        ),
        migrations.AddField(
            model_name='viden',
            name='favoritter',
            field=models.ManyToManyField(blank=True, related_name='viden_favorites', to=settings.AUTH_USER_MODEL, verbose_name='Favoritter'),
        ),
        migrations.AddField(
            model_name='viden',
            name='slettet',
            field=models.BooleanField(default=False, verbose_name='Slettet'),
        ),
    ]
