# Generated by Django 5.0.14 on 2026-03-10 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_company_uitranslation_alter_team_navn_team_company_and_more'),
        ('vidensbank', '0009_alter_viden_options_remove_viden_favorit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viden',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viden_artikler', to='core.company'),
        ),
        migrations.AddField(
            model_name='videnskategori',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videnskategorier', to='core.company'),
        ),
        migrations.AlterField(
            model_name='videnskategori',
            name='navn',
            field=models.CharField(max_length=100),
        ),
    ]
