# Generated by Django 5.0.14 on 2026-02-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aktivitet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=200)),
                ('beskrivelse', models.TextField(blank=True)),
                ('start_dato', models.DateField()),
                ('slut_dato', models.DateField()),
                ('farve', models.CharField(default='#3b82f6', max_length=7)),
                ('oprettet', models.DateTimeField(auto_now_add=True)),
                ('opdateret', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Aktivitet',
                'verbose_name_plural': 'Aktiviteter',
                'ordering': ['start_dato'],
            },
        ),
    ]
