# Generated by Django 5.0.14 on 2026-02-24 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aarshjul', '0001_initial'),
        ('core', '0005_userprofile_vidensbank_category_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='AarshjulGruppe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=100)),
                ('raekkefoelge', models.IntegerField(default=0)),
                ('oprettet', models.DateTimeField(auto_now_add=True)),
                ('teams', models.ManyToManyField(blank=True, related_name='aarshjul_grupper', to='core.team')),
            ],
            options={
                'verbose_name': 'Årshjul Gruppe',
                'verbose_name_plural': 'Årshjul Grupper',
                'ordering': ['raekkefoelge', 'navn'],
            },
        ),
        migrations.AddField(
            model_name='aktivitet',
            name='gruppe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aktiviteter', to='aarshjul.aarshjulgruppe'),
        ),
    ]
