# Generated by Django 5.0.14 on 2026-03-10 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aarshjul', '0002_aarshjulgruppe_aktivitet_gruppe'),
        ('core', '0006_company_uitranslation_alter_team_navn_team_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aarshjulgruppe',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aarshjul_grupper', to='core.company'),
        ),
        migrations.AddField(
            model_name='aktivitet',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aktiviteter', to='core.company'),
        ),
    ]
