# Generated by Django 5.0.14 on 2026-02-13 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('SUPERUSER', 'Superbruger'), ('MEMBER', 'Medlem')], default='MEMBER', max_length=20),
        ),
    ]
