# Generated by Django 5.0.14 on 2026-02-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='color',
            field=models.CharField(default='#3b82f6', max_length=20),
        ),
    ]
