# Generated by Django 5.2.11 on 2026-02-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_team_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='vidensbank_category_order',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
