# Generated by Django 5.0.14 on 2026-03-10 17:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userprofile_vidensbank_category_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('navn', models.CharField(max_length=255)),
                ('cvr', models.CharField(blank=True, max_length=20, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Virksomhed',
                'verbose_name_plural': 'Virksomheder',
            },
        ),
        migrations.CreateModel(
            name='UITranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('en', models.TextField(verbose_name='Engelsk (Base)')),
                ('da', models.TextField(blank=True, null=True, verbose_name='Dansk')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'UI Oversættelse',
                'verbose_name_plural': 'UI Oversættelser',
            },
        ),
        migrations.AlterField(
            model_name='team',
            name='navn',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='core.company'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='core.company'),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('navn', 'company')},
        ),
    ]
