# Generated by Django 5.0.14 on 2026-03-10 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_company_uitranslation_alter_team_navn_team_company_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrator'), ('SUPERUSER', 'Superbruger'), ('MEMBER', 'Medlem')], default='MEMBER', max_length=20)),
                ('alias', models.CharField(blank=True, help_text='Visningsnavn i dette arbejdsrum', max_length=255, null=True)),
                ('color', models.CharField(default='#3b82f6', max_length=20)),
                ('oprettet', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Arbejdsrum Medlemskab',
                'verbose_name_plural': 'Arbejdsrum Medlemskaber',
                'unique_together': {('user', 'company')},
            },
        ),
    ]
