# Generated by Django 5.0.14 on 2026-03-11 19:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(max_length=255)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Arbejdsrum forespørgsel',
                'verbose_name_plural': 'Arbejdsrum forespørgsler',
            },
        ),
    ]
