# Generated by Django 5.0.14 on 2026-03-11 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_workspacerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.CharField(default='da', help_text='Brugerens foretrukne sprog', max_length=10),
        ),
    ]
