# Generated by Django 5.2.11 on 2026-07-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_userprofile_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='uitranslation',
            name='de',
            field=models.TextField(blank=True, null=True, verbose_name='Tysk'),
        ),
        migrations.AddField(
            model_name='uitranslation',
            name='fr',
            field=models.TextField(blank=True, null=True, verbose_name='Fransk'),
        ),
        migrations.AddField(
            model_name='uitranslation',
            name='nl',
            field=models.TextField(blank=True, null=True, verbose_name='Nederlandsk'),
        ),
    ]
