# Generated by Django 5.2.11 on 2026-07-09 17:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_uitranslation_de_uitranslation_fr_uitranslation_nl'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='uitranslation',
            name='de',
            field=models.TextField(blank=True, null=True, verbose_name='Deutsch'),
        ),
        migrations.AlterField(
            model_name='uitranslation',
            name='fr',
            field=models.TextField(blank=True, null=True, verbose_name='Français'),
        ),
        migrations.AlterField(
            model_name='uitranslation',
            name='nl',
            field=models.TextField(blank=True, null=True, verbose_name='Nederlands'),
        ),
        migrations.CreateModel(
            name='PasswordResetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_resets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nulstilling af adgangskode anmodning',
                'verbose_name_plural': 'Nulstilling af adgangskode anmodninger',
            },
        ),
    ]
